#!/bin/sh
#[config]------------------------------------------------------------------------
MAC_BROWSER=Safari.app
#MAC_BROWSER=w3m
MAC_BROWSER="w3m -dump"
LINUX_BROWSER=x-www-browser
LINUX_BROWSER="w3m -dump"
UTF8MANPATH="/usr/local/share/man/ja_JP.UTF-8"

#[functions]------------------------------------------------------------------------
args_not_found() {
    echo "usage: cli_searcher [options] keyword"
    echo "options:"
    echo "  -n|--net             : man日本語ウェブ"
    echo "  --php                : phpマニュアル"
    echo "  --alc                : alc和英/和英"
    echo "  --archwiki           : archwiki"
    echo "  --stackoverflow      : stackoverflow"
    echo "  --qiita-tag          : qiitaタグ"
    echo "  --qiita              : qiita"
    echo "  --googlemap          : googleマップ"
    echo "  --gmail              : gmail"
    echo "  --google             : google"
    echo "  --smblookup          : Windowsのコンピュータ名検索"
    echo "  --whois_jp_contact   : jpドメイン名から登録者一覧を検索"
    echo "  --jobtalk            : 企業の内情"
    echo "  --kakaku             : 価格コム"
    echo "  --wikipedia          : wikipedia"
    echo "  --vimdoc             : vimdoc"
    echo "  --weather            : 天気"
    echo "  --youtube            : youtube"
    echo "  --github-python      : github code search"
    echo "  --github-php         : github code search"
    echo "  --github-html        : github code search"
    echo "  --github-javascript  : github code search"
    man
}

colorman() {
    env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
    exit 0
}

set_url() {
    URL="http://linuxjm.sourceforge.jp/cgi-bin/man.cgi?Pagename=%s&Sec1=on&Sec2=on&Sec3=on&Sec4=on&Sec5=on&Sec6=on&Sec7=on&Sec8=on"
    case "$1" in
        --php) URL="http://jp2.php.net/%s" ;;
        --alc) URL="http://eow.alc.co.jp/search?q=%s" ;;
        --archwiki) URL="https://wiki.archlinux.org/index.php/%s" ;;
        --stackoverflow) URL="http://stackoverflow.com/questions/tagged/%s" ;;
        --qiita) URL="http://qiita.com/search?q=%s" ;;
        --qiita-tag) URL="http://qiita.com/tags/%s" ;;
        --googlemap) URL="https://maps.google.co.jp/maps?saddr=%s" ;;
        --gmail) URL="https://mail.google.com/mail/u/0/?tab=wm#apps/%s" ;;
        --google) URL="http://www.google.co.jp/search?q=%s" ;;
        --jobtalk) URL="http://jobtalk.jp/company/keyword_%s_1.html" ;;
        --kakaku) URL="http://kakaku.com/search_results/%s" ;;
        --wikipedia) URL="http://ja.wikipedia.org/wiki/%s" ;;
        --weather) URL="http://search.weather.yahoo.co.jp/bin/search?p=%s" ;;
        --vimdoc) URL="http://vimdoc.sourceforge.net/search.php?docs=help&search=%s" ;;
        --youtube) URL="http://www.youtube.com/results?search_query=%s" ;;
        --github-python) URL="https://github.com/search?type=Code&l=python&q=%s" ;;
        --github-php) URL="https://github.com/search?type=Code&l=php&q=%s" ;;
        --github-html) URL="https://github.com/search?type=Code&l=html&q=%s" ;;
        --github-javascript) URL="https://github.com/search?type=Code&l=javascript&q=%s" ;;
    esac
    case "$2" in
        ssh|ssh_config|sshd|sshd_config|ssh-agent|ssh-add|scp|sftp|ssh-keygen|sftp-server|ssh-keyscan|ssh-keysign)
        URL="http://www.unixuser.org/~euske/doc/openssh/jman/%s" ;;
    esac
}

browse() {
    if [ "$(uname -s)" = "Darwin" ];then
        if [ "${MAC_BROWSER: -4}" = ".app" ];then
            open -a ${MAC_BROWSER} ${1}
        else
            ${MAC_BROWSER} ${1} ${2}
        fi
    else
        ${LINUX_BROWSER} ${1}
    fi
}

url_encode() {
    URL_ENCODED=$(python -c "import sys, urllib; print urllib.quote_plus(sys.argv[1])" "$1")
}

whois_jp_contact() {
    DIG_IP=$(dig +short $1)
    if [ "$DIG_IP" = "" ];then
        echo "[quit] $1 のIPアドレスが引けませんでした。"
        exit 1
    fi
    whois $DIG_IP | grep inetnum | tail -n 1
    WHOIS=$(whois -h whois2013.jprs.jp $1 | awk -F "]" '/登録者名|組織名/{$1="";print}')
    url_encode "$(echo $WHOIS | nkf -s)"
    WHOIS=${URL_ENCODED}
    browse "http://whois.nic.ad.jp/cgi-bin/whois_gw?key=${WHOIS}&type=CONTACT"
}

# whois_jp_contact で取得できないパターン用。
whois_jp_contact2() {
    DOMAINNAME=${1}
    DIG_IP=$(dig +short $DOMAINNAME)
    if [ "$DIG_IP" = "" ];then
        echo "[quit] $DOMAINNAME のIPアドレスが引けませんでした。"
        exit 1
    fi
    WHOIS="whois -h whois2013.jprs.jp"
    #
    IP_RANGE=$(${WHOIS} $DIG_IP | grep "inetnum" | cut -d "]" -f 2)
    if [ "$IP_RANGE" = "" ];then
        echo "[info] $DOMAINNAME のIP範囲が引けませんでした。"
    else
        echo "[info] IP Range : $IP_RANGE"
    fi
    #
    NAMESERVER=$(${WHOIS} ${DOMAINNAME}/e | grep "Name Server" | head -n 1 | cut -d "]" -f 2)
    if [ "$NAMESERVER" = "" ];then
      echo "[quit] $DOMAINNAME の Name Server が引けませんでした。"
      exit 1
    fi
    echo "[info] Name Server : ${NAMESERVER}"
    #
    T_CONTACT=$(${WHOIS} ${NAMESERVER}/e | grep "Technical Contact" | cut -d "]" -f 2)
    if [ "$T_CONTACT" = "" ];then
      echo "[quit] $DOMAINNAME の Technical Contact が引けませんでした。"
      exit 1
    fi
    echo "[info] Technical Contact : ${T_CONTACT}"
    #
    ORGANIZATION=$(${WHOIS} ${T_CONTACT} | nkf -w | grep "組織名" | cut -d "]" -f 2)
    if [ "$ORGANIZATION" = "" ];then
      echo "[quit] $DOMAINNAME の 組織名 が引けませんでした。"
      exit 1
    fi
    echo "[info] 組織名 : ${ORGANIZATION}"
    #
    whois_jp_browse ${ORGANIZATION}
}

whois_jp_browse() {
    url_encode "$(echo $1 | nkf -s)"
    browse "http://whois.nic.ad.jp/cgi-bin/whois_gw?key=${URL_ENCODED}&type=CONTACT"
}

#[main]---------------------------------------------------------------------------
if [ "$1" = "" ];then
    args_not_found
    exit 0
fi

if [ -d "$UTF8MANPATH" ];then
    export MANPATH=${UTF8MANPATH}:${MANPATH}
fi

## colorman
case "$1" in
    -n|--net|\
    --php|\
    --alc|\
    --archwiki|\
    --stackoverflow|\
    --qiita|--qiita-tag|\
    --googlemap|\
    --gmail|\
    --google|\
    --jobtalk|\
    --kakaku|\
    --wikipedia|\
    --vimdoc|\
    --weather|\
    --youtube|\
    --github-python|--github-php|--github-html|--github-javascript)
    ;;
    --smblookup)
    smbutil lookup $2
    exit 0
    ;;
    --whois_jp_contact)
    whois_jp_contact $2
    exit 0
    ;;
    --whois_jp_contact2)
    whois_jp_contact $2
    exit 0
    ;;
    *)
    colorman $@
    ;;
esac

## set_url
set_url $1 $2

## join search words
for query in "$@"
do
    if [ "$query" = "$0" ];then continue;fi
    if [ "$query" = "$1" ];then continue;fi
    if [ "$SEARCHWORD" = "" ];then
        SEARCHWORD=$query
    else
        SEARCHWORD="${SEARCHWORD} $query"
    fi
done

url_encode "$SEARCHWORD"

## browse
URL=$(printf ${URL} ${URL_ENCODED})

if [ $1 = "-n" -o $1 = "--net" ];then
    URL=$(curl -s -I $URL | grep "Location:" | cut -d " " -f 2)
    # URLに %0D がくっ付くので改行コード削除
    URL=$(echo $URL | tr -d '\r')
    URL=$(echo $URL | tr -d '\n')
    echo $URL | grep nosuchpage
    if [ $? == 0 ]; then echo "[quit] page not found."; exit 0; fi
fi
echo [browse] $URL

browse $URL
