#!/bin/sh
#[config]------------------------------------------------------------------------
MAC_BROWSER=/Applications/Safari.app
#MAC_BROWSER=/usr/local/bin/w3m
LINUX_BROWSER=x-www-browser
UTF8MANPATH="/usr/local/share/man/ja_JP.UTF-8"

#[functions]------------------------------------------------------------------------
args_not_found() {
    echo "usage: cli_searcher [options] keyword"
    echo "options:"
    echo "  -n|--net             : man日本語ウェブ"
    echo "  --php                : phpマニュアル"
    echo "  --alc                : alc和英/和英"
    echo "  --archwiki           : archwiki"
    echo "  --stackoverflow      : stackoverflow"
    echo "  --qiita-tag          : qiitaタグ"
    echo "  --qiita              : qiita"
    echo "  --googlemap          : googleマップ"
    echo "  --google             : google"
    echo "  --smblookup          : Windowsのコンピュータ名検索"
    echo "  --jobtalk            : 企業の内情"
    echo "  --kakaku             : 価格コム"
    echo "  --wikipedia          : wikipedia"
    echo "  --weather            : 天気"
    echo "  --youtube            : youtube"
    echo "  --github-python      : github code search"
    echo "  --github-php         : github code search"
    echo "  --github-html        : github code search"
    echo "  --github-javascript  : github code search"
    man
}

colorman() {
    env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
    exit 0
}

set_url() {
    URL="http://linuxjm.sourceforge.jp/cgi-bin/man.cgi?Pagename=%s"
    case "$1" in
        --php) URL="http://jp2.php.net/%s" ;;
        --alc) URL="http://eow.alc.co.jp/search?q=%s" ;;
        --archwiki) URL="https://wiki.archlinux.org/index.php/%s" ;;
        --stackoverflow) URL="http://stackoverflow.com/questions/tagged/%s" ;;
        --qiita) URL="http://qiita.com/search?q=%s" ;;
        --qiita-tag) URL="http://qiita.com/tags/%s" ;;
        --googlemap) URL="https://maps.google.co.jp/maps?saddr=%s" ;;
        --google) URL="http://www.google.co.jp/search?q=%s" ;;
        --jobtalk) URL="http://jobtalk.jp/company/keyword_%s_1.html" ;;
        --kakaku) URL="http://kakaku.com/search_results/%s" ;;
        --wikipedia) URL="http://ja.wikipedia.org/wiki/%s" ;;
        --weather) URL="http://search.weather.yahoo.co.jp/bin/search?p=%s" ;;
        --youtube) URL="http://www.youtube.com/results?search_query=%s" ;;
        --github-python) URL="https://github.com/search?type=Code&l=python&q=%s" ;;
        --github-php) URL="https://github.com/search?type=Code&l=php&q=%s" ;;
        --github-html) URL="https://github.com/search?type=Code&l=html&q=%s" ;;
        --github-javascript) URL="https://github.com/search?type=Code&l=javascript&q=%s" ;;
    esac
    case "$2" in
        ssh|ssh_config|sshd|sshd_config|ssh-agent|ssh-add|scp|sftp|ssh-keygen|sftp-server|ssh-keyscan|ssh-keysign)
        URL="http://www.unixuser.org/~euske/doc/openssh/jman/%s" ;;
    esac
}

browse() {
    if [ "`uname -s`" = "Darwin" ];then
        if [ "${MAC_BROWSER: -4}" = ".app" ];then
            open ${MAC_BROWSER} ${1}
        else
            ${MAC_BROWSER} ${1}
        fi
    else
        ${LINUX_BROWSER} ${1}
    fi
}

#[main]---------------------------------------------------------------------------
if [ "$1" = "" ];then
    args_not_found
    exit 0
fi

if [ -d "$UTF8MANPATH" ];then
    export MANPATH=${UTF8MANPATH}:${MANPATH}
fi

## colorman
case "$1" in
    -n|--net|\
    --php|\
    --alc|\
    --archwiki|\
    --stackoverflow|\
    --qiita|--qiita-tag|\
    --googlemap|\
    --google|\
    --jobtalk|\
    --kakaku|\
    --wikipedia|\
    --weather|\
    --youtube|\
    --github-python|--github-php|--github-html|--github-javascript)
    ;;
    --smblookup)
    smbutil lookup $2
    exit 0
    ;;
    *)
    colorman $@
    ;;
esac

## set_url
set_url $1 $2

## join search words
for query in "$@"
do
    if [ "$query" = "$0" ];then continue;fi
    if [ "$query" = "$1" ];then continue;fi
    if [ "$SEARCHWORD" = "" ];then
        SEARCHWORD=$query
    else
        SEARCHWORD=${SEARCHWORD}+$query
    fi
done

## browse
URL=`printf ${URL} ${SEARCHWORD}`
echo [browse] $URL
browse $URL
