#!/bin/sh
#[config]------------------------------------------------------------------------
MAC_BROWSER=/Applications/Safari.app
LINUX_BROWSER=x-www-browser
UTF8MANPATH="/usr/local/share/man/ja_JP.UTF-8"

#[functions]------------------------------------------------------------------------
args_not_found() {
    echo "options:"
    echo "  -n|--net <command>     : JP Project manpage."
    echo "  --php <function>       : http://jp2.php.net/%s"
    echo "  --alc <word>           : http://eow.alc.co.jp/search?q=%s"
    echo "  --archwiki <word>      : https://wiki.archlinux.org/index.php/%s"
    echo "  --stackoverflow <word> : http://stackoverflow.com/questions/tagged/%s"
    echo "  --qiita-tag <tagname>  : http://qiita.com/tags/%s"
    echo "  --qiita <word>         : http://qiita.com/search?q=%s"
    echo "  --googlemap <word>     : https://maps.google.co.jp/maps?saddr=%s"
    echo "  --google <word>        : http://www.google.co.jp/search?q=%s"
    echo "  --smblookup <pc_name>  : smbutil lookup <pc_name>"
    echo "  --jobtalk <company>    : http://jobtalk.jp/company/keyword_%s_1.html"
    man
}

colorman() {
    env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
    exit 0
}

set_url() {
    URL="http://linuxjm.sourceforge.jp/cgi-bin/man.cgi?Pagename=%s"
    case "$1" in
        "--php") URL="http://jp2.php.net/%s" ;;
        "--alc") URL="http://eow.alc.co.jp/search?q=%s" ;;
        "--archwiki") URL="https://wiki.archlinux.org/index.php/%s" ;;
        "--stackoverflow") URL="http://stackoverflow.com/questions/tagged/%s" ;;
        "--qiita") URL="http://qiita.com/search?q=%s" ;;
        "--qiita-tag") URL="http://qiita.com/tags/%s" ;;
        "--googlemap") URL="https://maps.google.co.jp/maps?saddr=%s" ;;
        "--google") URL="http://www.google.co.jp/search?q=%s" ;;
        "--jobtalk") URL="http://jobtalk.jp/company/keyword_%s_1.html" ;;
    esac
    case "$2" in
        ssh|ssh_config|sshd|sshd_config|ssh-agent|ssh-add|scp|sftp|ssh-keygen|sftp-server|ssh-keyscan|ssh-keysign)
        URL="http://www.unixuser.org/~euske/doc/openssh/jman/%s" ;;
    esac
}

browse() {
    if [ "`uname -s`" = "Darwin" ];then
        open ${MAC_BROWSER} ${1}
    else
        ${LINUX_BROWSER} ${1}
    fi
}

#[main]---------------------------------------------------------------------------
if [ "$1" = "" ];then
    args_not_found
    exit 0
fi

if [ -d "$UTF8MANPATH" ];then
    export MANPATH=${UTF8MANPATH}:${MANPATH}
fi

## colorman
case "$1" in
    -n|--net|\
    --php|\
    --alc|\
    --archwiki|\
    --stackoverflow|\
    --qiita|--qiita-tag|\
    --googlemap|\
    --google|\
    --jobtalk)
    ;;
    --smblookup)
    smbutil lookup $2
    exit 0
    ;;
    *)
    colorman $@
    ;;
esac

## set_url
set_url $1 $2

## join search words
for query in "$@"
do
    if [ "$query" = "$0" ];then continue;fi
    if [ "$query" = "$1" ];then continue;fi
    if [ "$SEARCHWORD" = "" ];then
        SEARCHWORD=$query
    else
        SEARCHWORD=${SEARCHWORD}+$query
    fi
done

## browse
URL=`printf ${URL} ${SEARCHWORD}`
echo [browse] $URL
browse $URL
